In [1]:
!pip list

Package             Version
------------------- -----------
asttokens           2.4.1
certifi             2024.2.2
charset-normalizer  3.3.2
click               8.1.7
cloudpickle         3.0.0
colorama            0.4.6
comm                0.2.2
contourpy           1.2.0
CSIKit              2.5
cycler              0.12.1
dask                2024.4.0
dask-expr           1.0.6
debugpy             1.8.1
decorator           5.1.1
distributed         2024.4.0
et-xmlfile          1.1.0
executing           2.0.1
featuretools        1.30.0
fonttools           4.50.0
fsspec              2024.3.1
holidays            0.46
idna                3.6
importlib_resources 6.4.0
ipykernel           6.29.4
ipython             8.25.0
jedi                0.19.1
Jinja2              3.1.3
joblib              1.3.2
jupyter_client      8.6.2
jupyter_core        5.7.2
kiwisolver          1.4.5
locket              1.0.0
MarkupSafe          2.1.5
matplotlib          3.8.3
matplotlib-inline   0.1.7
msgpack             1.0.8
nest-asyncio        1.6.0
numpy               1.26.4
openpyxl            3.1.0
packaging           24.0
panda               0.3.1
pandas              2.2.1
parso               0.8.4
partd               1.4.1
pillow              10.2.0
pip                 24.0
platformdirs        4.2.2
prompt_toolkit      3.0.45
psutil              5.9.8
pure-eval           0.2.2
pyarrow             15.0.2
Pygments            2.18.0
pyparsing           3.1.2
python-dateutil     2.9.0.post0
pytz                2024.1
PyWavelets          1.6.0
pywin32             306
PyYAML              6.0.1
pyzmq               26.0.3
requests            2.31.0
scikit-learn        1.4.1.post1
scipy               1.12.0
seaborn             0.13.2
setuptools          69.2.0
six                 1.16.0
sortedcontainers    2.4.0
stack-data          0.6.3
tblib               3.0.0
threadpoolctl       3.4.0
toolz               0.12.1
tornado             6.4
tqdm                4.66.2
traitlets           5.14.3
tzdata              2024.1
urllib3             2.2.1
wcwidth             0.2.13
woodwork            0.29.0
xgboost             2.0.3
xlrd                2.0.1
zict                3.0.0

In [2]:
import featuretools as ft
import pandas as pd

In [4]:
data=pd.read_csv("../00_Data/Integrated_data/integration_b.csv",encoding="utf-8")
data.head()

,Date,Total Traffic Volume,Exchange Rate,Gross Domestic Product (GDP),Export growth rate,Import growth rate,Nationwide Consumer Price Index,Regular Unleaded Gasoline,Diesel Fuel for Automobiles,number of car ownership,Economic Growth Rate,Interest Rate Category,Export Price Category,Import Price Category
0,2011-01-01,5466446.0,1121.500000,328096.0,44.700000,13.600000,90.448000,1814.57,1611.14,18409608,High Growth,Low,Low,Medium
1,2011-01-02,5059821.0,1121.732258,328096.0,43.775943,13.521635,90.397806,1815.24,1611.79,18398782,High Growth,Low,Low,Medium
2,2011-01-03,5631394.0,1121.964516,328096.0,42.851885,13.443269,90.347613,1816.15,1612.85,18387956,High Growth,Low,Low,Medium
3,2011-01-04,5584995.0,1122.196774,328096.0,41.927828,13.364904,90.297419,1817.48,1614.02,18377130,High Growth,Low,Low,Medium
4,2011-01-05,5742955.0,1122.429032,328096.0,41.003771,13.286539,90.247226,1818.53,1615.00,18366304,High Growth,Low,Low,Medium

In [5]:
# Create an entity set
es = ft.EntitySet(id='economic_data')

# Add the data as an entity
es = es.add_dataframe(dataframe_name='data', dataframe=data, index='index', make_index=True)

# Run deep feature synthesis (DFS) to create new features
feature_matrix, feature_defs = ft.dfs(
    entityset=es,
    target_dataframe_name='data',
    agg_primitives=['mean', 'sum', 'min', 'max', 'std','count'],
    trans_primitives=['month', 'year', 'diff'],
    max_depth=5) 

feature_matrix.head()

c:\Python312\Lib\site-packages\woodwork\type_sys\utils.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
c:\Python312\Lib\site-packages\woodwork\type_sys\utils.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
c:\Python312\Lib\site-packages\woodwork\type_sys\utils.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
c:\Python312\Lib\site-packages\woodwork\type_sys\utils.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
c:\Python312\Lib\site-packages\woodwork\type_sys\utils.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
c:\Python312\Lib\site-packages\woodwork\type_sys\utils.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
c:\Python312\Lib\site-packages\woodwork\type_sys\utils.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
c:\Python312\Lib\site-packages\woodwork\type_sys\utils.py:40: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.to_datetime(
c:\Python312\Lib\site-packages\featuretools\synthesis\deep_feature_synthesis.py:169: UserWarning: Only one dataframe in entityset, changing max_depth to 1 since deeper features cannot be created
  warnings.warn(
c:\Python312\Lib\site-packages\featuretools\synthesis\dfs.py:321: UnusedPrimitiveWarning: Some specified primitives were not used during DFS:
  agg_primitives: ['count', 'max', 'mean', 'min', 'std', 'sum']
This may be caused by a using a value of max_depth that is too small, not setting interesting values, or it may indicate no compatible columns for the primitive were found in the data. If the DFS call contained multiple instances of a primitive in the list above, none of them were used.
  warnings.warn(warning_msg, UnusedPrimitiveWarning)

,Total Traffic Volume,Exchange Rate,Gross Domestic Product (GDP),Export growth rate,Import growth rate,Nationwide Consumer Price Index,Regular Unleaded Gasoline,Diesel Fuel for Automobiles,number of car ownership,Economic Growth Rate,...,DIFF(Exchange Rate),DIFF(Export growth rate),DIFF(Gross Domestic Product (GDP)),DIFF(Import growth rate),DIFF(Nationwide Consumer Price Index),DIFF(Regular Unleaded Gasoline),DIFF(Total Traffic Volume),DIFF(number of car ownership),MONTH(Date),YEAR(Date)
index,,,,,,,,,,,,,,,,,,,,,
0,5466446.0,1121.500000,328096.0,44.700000,13.600000,90.448000,1814.57,1611.14,18409608,High Growth,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2011
1,5059821.0,1121.732258,328096.0,43.775943,13.521635,90.397806,1815.24,1611.79,18398782,High Growth,...,0.232258,-0.924057,0.0,-0.078365,-0.050194,0.67,-406625.0,-10826.0,1,2011
2,5631394.0,1121.964516,328096.0,42.851885,13.443269,90.347613,1816.15,1612.85,18387956,High Growth,...,0.232258,-0.924057,0.0,-0.078365,-0.050194,0.91,571573.0,-10826.0,1,2011
3,5584995.0,1122.196774,328096.0,41.927828,13.364904,90.297419,1817.48,1614.02,18377130,High Growth,...,0.232258,-0.924057,0.0,-0.078365,-0.050194,1.33,-46399.0,-10826.0,1,2011
4,5742955.0,1122.429032,328096.0,41.003771,13.286539,90.247226,1818.53,1615.00,18366304,High Growth,...,0.232258,-0.924057,0.0,-0.078365,-0.050194,1.05,157960.0,-10826.0,1,2011

In [6]:
print([f.get_name() for f in feature_defs])

['Total Traffic Volume', 'Exchange Rate', 'Gross Domestic Product (GDP)', 'Export growth rate', 'Import growth rate', 'Nationwide Consumer Price Index', 'Regular Unleaded Gasoline', 'Diesel Fuel for Automobiles', 'number of car ownership', 'Economic Growth Rate', 'Interest Rate Category', 'Export Price Category', 'Import Price Category', 'DIFF(Diesel Fuel for Automobiles)', 'DIFF(Exchange Rate)', 'DIFF(Export growth rate)', 'DIFF(Gross Domestic Product (GDP))', 'DIFF(Import growth rate)', 'DIFF(Nationwide Consumer Price Index)', 'DIFF(Regular Unleaded Gasoline)', 'DIFF(Total Traffic Volume)', 'DIFF(number of car ownership)', 'MONTH(Date)', 'YEAR(Date)']